# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - hydra: default
  - model: tree_pseco
  - data: noasca_vda
  - training: cls_head
  - _self_

# seed for random number generators in pytorch, numpy and python.random
seed: 99
# Validation
val_only: false

slurm_output_dir: outputs/cls_head_new/${now:%Y-%m-%d}_${now:%H-%M-%S}

hydra:
  run:
    dir: ${hydra:runtime.cwd}/${slurm_output_dir}
  sweep:
    dir: ${hydra:runtime.cwd}/${slurm_output_dir}

model:
  heatmap_box_detector:
    himn: 0.3
  roi_head_classifier:
    accept_heatmap: false
    accept_rgb: false
    use_rn50: true
  freeze_rn50_body: false

training:
  point_decoder_ckpt: pretrained/point_decoder/pt_dec_neon_pretrain_loss_04006.pth
  rn50_ckpt: pretrained/rn50/NEON.pt
  log_every_n_steps: 2
  viz_n_train_images: 1
  viz_n_val_images: 2