# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - model: point_decoder_finetune
  - data: noasca_vda
  - training: point_decoder_finetune
  - _self_

slurm_output_dir: outputs/neon_tree_point_decoder_finetune_noasca_vda/${now:%Y-%m-%d}_${now:%H-%M-%S}

hydra:
  run:
    dir: ${hydra:runtime.cwd}/${slurm_output_dir}
  sweep:
    dir: ${hydra:runtime.cwd}/${slurm_output_dir}

seed: 99
val_only: false

model:
  point_decoder:
    mask_upscaling_type: default # bilinear
    point_decoder_state_dict_path: pretrained/point_decoder/pt_dec_neon_pretrain_loss_04006.pth
    prefix_to_rmv_in_state_dict: "pretrain_sam_point_decoder."

training:
  loss_type: mse # ssim
  log_every_n_steps: 2
  viz_n_train_images: 1
  viz_n_val_images: 2
